-- PG 专有：同步 IDENTITY 序列（种子用显式 id 插入后推进 BIGSERIAL 序列）。
-- 本文件位于 db/migration/postgresql/ 目录，Flyway 按 {vendor} 占位符仅在 PostgreSQL 上执行。
-- H2（测试）的 GENERATED BY DEFAULT AS IDENTITY 自动推进，无需 setval。
-- 种子用显式 id 插入会绕过序列推进，导致后续 JPA 插入 nextval 返回旧值引发主键冲突。
-- 本文件在所有模块种子（V1__init.sql）之后执行（V99），确保序列已推进。

SELECT setval('sys_user_id_seq', COALESCE((SELECT MAX(id) FROM sys_user), 0) + 1, false);
SELECT setval('sys_role_id_seq', COALESCE((SELECT MAX(id) FROM sys_role), 0) + 1, false);
SELECT setval('sys_menu_id_seq', COALESCE((SELECT MAX(id) FROM sys_menu), 0) + 1, false);
SELECT setval('sys_unit_id_seq', COALESCE((SELECT MAX(id) FROM sys_unit), 0) + 1, false);
SELECT setval('sys_config_id_seq', COALESCE((SELECT MAX(id) FROM sys_config), 0) + 1, false);
